name: Stellar Expert WASM Release
on:
  push: 
    tags:
      - 'v*'  # triggered whenever a new tag (previxed with "v") is pushed to the repository
jobs:
  release-contract-backstop:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Blend Backstop Release'
      package: 'backstop'
      make_target: 'build'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  release-contract-pool:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Blend Pool Release'
      package: 'pool'
      make_target: 'build'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  release-contract-emitter:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Blend Emitter Release'
      package: 'emitter'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  release-contract-pool-factory:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Blend Pool Factory Release'
      package: 'pool-factory'
      make_target: 'build'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
